### ISSUE TITLE
Force address mode?

### ISSUE THREAD

**Issue by Herringway** [kleinesfilmroellchen/spcasm#130]
Is there a way to override the direct page detection? For example, I'd like `MOV $00F1, A` to assemble to `C5 F1 00` instead of `C4 F1`.

**Comment by kleinesfilmroellchen** [comment]
There is currently no way of forcing an instruction into not using direct page mode. The inverse with `.b` is a feature borrowed from Asar, which to my knowledge also doesn't have this feature. I assume your application is specific instruction timings and sizes? The feature doesn't sound generally useful, but it shouldn't be too complicated.

**Comment by Herringway** [comment]
Yeah, specific sizes. I don't know the original code's intent with this, I'm just disassembling it for now.

**Comment by kleinesfilmroellchen** [comment]
Disassembly is a very interesting use case actually, I was already thinking about creating a disassembler based on spcasm's intermediate representation... Either way, this feature should be ready in a little bit once I have the few last bugs fixed.
